name: build_task
description: Build v8 task.
title: "[BUILD]: [DATE]"
labels: ["build"]

body:
  - type: input
    id: commit
    attributes:
      label: ">>commit_id<<"
      description: build commit id
      placeholder: "0"
    validations:
      required: true
  - type: checkboxes
    id: upload_depot
    attributes:
      label: ">>upload_depot_files<<"
      description: upload 
      options:
        - label: enable
          required: true
  - type: checkboxes
    id: upload_src
    attributes:
      label: ">>upload_v8_files<<"
      description: upload 
      options:
        - label: enable
          required: true
