name: build_task
description: Build v8 task.
title: "BUILD TASK: [DATE] [COMMIT]"
labels: ["build task"]

body:
  - type: input
    id: commit
    attributes:
      label: ">>commit_id<<"
      description: build commit id
      placeholder: "0"
      value: "0"
    validations:
      required: true
  
  - type: dropdown
    id: build_env
    attributes:
      label: ">>build_env<<"
      options:
        - ubuntu
        - mac
    validations:
      required: true
  
  - type: checkboxes
    id: build_v8
    attributes:
      label: ">>build_v8<<"
      description: Build v8 files. 
      options:
        - label: enable

  - type: checkboxes
    id: upload_depot
    attributes:
      label: ">>upload_depot<<"
      description: Upload depot files to cowtransfer
      options:
        - label: enable

  - type: checkboxes
    id: upload_src
    attributes:
      label: ">>upload_v8<<"
      description: Upload v8 files to cowtransfer
      options:
        - label: enable
          
  - type: checkboxes
    id: clean_git
    attributes:
      label: ">>clean_git<<"
      description: Clean git files to minify the package size.
      options:
        - label: enable
