# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
   types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ParseIssue
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'

      - name: args
        id: args
        run: |
          echo "commit id: $${{ fromJson(steps.parse.outputs.payload).commit_id }}"
          echo "::set-output name=commit_id::$${{ fromJson(steps.parse.outputs.payload).commit_id }}"
  
      - name: patch v8
        if: steps.args.outputs.commit_id != '0' && !cancelled()
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "args: ${{steps.args.outputs}}"
          echo "commit id: ${{steps.args.outputs.commit_id}}"
